### ISSUE TITLE
能正常分享到qq，但有错误提示。

### ISSUE THREAD

**Issue by yulinho** [reactnativecn/react-native-qq#10]
manifestPlaceholders = [
            QQ_APPID: "***"
        ]
build.gradle 中 appid已设置正确。
[StatDispatcher(1402): null:-1] - Server response error code:404, error:{"ret":-1, "msg":"invalid appkey"}

**Comment by cham1985** [comment]
@yulinho  你分享是调的 shareToQzone 函数么, 参数 webpageUrl 你怎么填的 ?

**Comment by cham1985** [comment]
var result = await QQAPI.shareToQzone(
                // 分享图文消息
                {
                    type: 'news',
                    title: '来自RN 项目的分享 标题',
                    description: '来自RN 项目的分享 描述',
                    webpageUrl: 'www.extrabux.com',
                    imageUrl: 'www.extrabux.com'
                }
            );
我返回 targetUrl 有误 ,楼猪能解不

**Comment by gordonpro** [comment]
同样遇到此问题

**Comment by gordonpro** [comment]
能正确分享，但是
`Server response error code:404, error:{"ret":-1, "msg":"invalid appkey"}`

**Comment by tdzl2003** [comment]
QQ appID必须为移动应用，如果为平台应用无法分享，别的问题我这里也没遇到过，建议查询QQ的文档或者在QQ SDK社区咨询。

**Comment by longzaitian** [comment]
@gordonpro解决了吗？碰到同样问题

**Comment by gordonpro** [comment]
@longzaitian 没有，我这里不影响正常使用
