### ISSUE TITLE
有没有判断未安装QQ的方法？

### ISSUE THREAD

**Issue by asolas** [reactnativecn/react-native-qq#18]
判断是否安装了QQ
已经安装再执行现在的
没有安装的时候toust一条信息
这种

**Comment by crystalxmumu** [comment]
同求

**Comment by tdzl2003** [comment]
目前QQ SDK自身的安卓版就没有这个接口，所以只能在iOS上支持这个功能。

**Comment by crystalxmumu** [comment]
@tdzl2003 好滴，麻烦在ios上提供这个接口，这样好是否显示qq登录、分享这些功能，否则直接显示的话，审核会被拒绝
