### ISSUE TITLE
能否升级下ios版本中的QQ SDK文件

### ISSUE THREAD

**Issue by crystalxmumu** [reactnativecn/react-native-qq#21]
你好，现在的版本中 如果用户没有安装QQ的话，分享到QQ和分享到QZone没有任何效果，api中也没有提供用户是否安装qq的方法，如果提交App Store的话，肯定会被退回。新版本中关于分享提到了在用户安装了手机 QQ 时通过手机 QQ 进行分享，否则调用浏览器页面进行分享。
ios qq sdk [下载地址：](http://wiki.open.qq.com/wiki/mobile/SDK%E4%B8%8B%E8%BD%BD)

我这边直接替换TencentOpenAPI.framework 文件，编译报错，
` "l_OBJC_PROTOCOL_$_TencentApiInterfaceDelegate", referenced from:
      l_OBJC_$_PROTOCOL_REFS_TencentSessionDelegate in libRCTQQAPI.a(RCTQQAPI.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

这边对ios了解不多，可否升级下ios版本中的QQ SDK文件，谢谢

**Comment by tdzl2003** [comment]
已经更新

**Comment by crystalxmumu** [comment]
@tdzl2003 谢谢~
