### ISSUE TITLE
qq登陆没有回调

### ISSUE THREAD

**Issue by yabinliu** [reactnativecn/react-native-qq#25]

**Comment by litingjun2015** [comment]
我测安卓版本也有这个问题，qq登录界面能出现，点击授权后就返回主界面了，没有回调。

react-native-cli: 1.0.0
react-native: 0.34.1

试过 [pull-28](https://github.com/reactnativecn/react-native-qq/pull/28) 也不行。

我的应用在“腾讯开放平台”还没通过审核，和这个有关吗？

烦请作者看一下，谢谢！

**Comment by yabinliu** [comment]
解决了吗

**Comment by litingjun2015** [comment]
还没

**Comment by litingjun2015** [comment]
我的解决了，应该是App需要先在腾讯开放平台http://open.qq.com/审核通过。
