### ISSUE TITLE
在0.33.0版本怎么添加onActivityResult实现？

### ISSUE THREAD

**Issue by dengsgo** [reactnativecn/react-native-qq#26]
RT

**Comment by sunnylqm** [comment]
http://facebook.github.io/react-native/docs/native-modules-android.html#getting-activity-result-from-startactivityforresult

**Comment by dengsgo** [comment]
问题已解决，详见PR[pull-28](https://github.com/reactnativecn/react-native-qq/pull/28)

**Comment by America-first-melon** [comment]
咋弄  看pull-28 不是很明白啊

**Comment by tdzl2003** [comment]
现在应当不需要手动添加onActivityResult了
