### ISSUE TITLE
更好的文档

### ISSUE THREAD

**Issue by kinhunt** [reactnativecn/react-native-qq#3]
Cool project。建议一步完善文档，包括如何 iOS 安装，以及获得 promise 返回的 token 之后如何拉取用户信息。最好有个完整功能的 Example，谢谢。Good day。

**Comment by tdzl2003** [comment]
前面的文档有空的时候会完善，同时也欢迎先行者PR帮助改善文档：）

关于获取token之后如何拉取信息，这一部分是通过http直接与graph.qq.com交互，建议阅读QQ开放平台官方文档。

**Comment by tdzl2003** [comment]
https://github.com/tdzl2003/wp_plugin_collections/blob/master/app-qq-login/src/api.php

这里刚好有一个我前段时间用PHP写的例子，是wordpress中的插件，可以参考。

**Comment by kinhunt** [comment]
@tdzl2003 谢谢，获取用户信息的资料挺好查的。iOS 的安装可以提供一下吗？I tried：

1. npm 安装模块
2. 把 RCTQQAPI 拉到 XCODE，并加入到 Build Phrase -> Link Libraries
3. 把 TencentOpenAPI. framework 拉到 XCODE，并加入到 Build Phrase -> Link Libraries

真机编译运行通过，单调用 Login 无反应。

请问还缺些什么？谢谢。

**Comment by tdzl2003** [comment]
@lvbingru 看一下

**Comment by tdzl2003** [comment]
@kinhunt 我们刚刚在npm发布了一个新版本，除了添加和完善了安装文档，iOS的实现也有所变化，其中包含了基于RN 0.17的LinkingIOS的回调处理，可以看看是否解决了您的问题：）
