### ISSUE TITLE
已经全部按照要求添加了相关依赖，但还是报这个错误，在模拟器上使用的时候。

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [reactnativecn/react-native-qq#35]
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_QQApiAudioObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiImageObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiInterface", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiNewsObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiTextObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiVideoObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_SendMessageToQQReq", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_SendMessageToQQResp", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_TencentOAuth", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

已经全部按照要求添加了相关依赖，但还是报这个错误，在模拟器上使用的时候。

**Comment by Darkhorse-Fraternity** [comment]
真机运行正常，看来只是模拟器上有问题

**Comment by mogazheng** [comment]
我也是这个问题

**Comment by HiddenGithub** [comment]
我也遇到了这个报错,可是我的不管在模拟器还是真机都跑不了!这个问题你怎么解决的,求指教

**Comment by Darkhorse-Fraternity** [comment]
ld: warning: ignoring file ../node_modules/react-native-qq/ios/RCTQQAPI/TencentOpenAPI.framework/TencentOpenAPI, missing required architecture i386 in file ../node_modules/react-native-qq/ios/RCTQQAPI/TencentOpenAPI.framework/TencentOpenAPI (3 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_SendMessageToQQReq", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiVideoObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiAudioObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiNewsObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiImageObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiTextObject", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_SendMessageToQQResp", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_QQApiInterface", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
  "_OBJC_CLASS_$_TencentOAuth", referenced from:
      objc-class-ref in libRCTQQAPI.a(RCTQQAPI.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

我只在模拟器上release 模式下碰到这个问题。rn0.40

**Comment by imtcn** [comment]
+1
