### ISSUE TITLE
Android配置上的问题

### ISSUE THREAD

**Issue by ailinyt** [reactnativecn/react-native-qq#39]
根据README
![wechatimg10](https://cloud.githubusercontent.com/assets/8371161/21001280/6c4194b8-bd5a-11e6-84a3-eb9961cca214.jpeg)
可能由于React Native版本更新的问题，我在进行红框内的配置的时候遇到了问题。比如：我在`MainActivity.java`这个文件中找不到`.addPackage(new MainReactPackage())`这个语句，所以也没办法增加` .addPackage(new QQPackage())`。
我想请教一下具体应该如何配置？

**Comment by sunnylqm** [comment]
现在是在MainApplication.java中配置，结构有细微变动，但仔细看你自己应该能对应上
