### ISSUE TITLE
RN0.29，安卓版是不是不用加onActivityResult?

### ISSUE THREAD

**Issue by maagee** [reactnativecn/react-native-qq#42]
MainActivity.java是不是不用加onActivityResult ？

但是还报错：
/node_modules/react-native-qq/android/src/main/java/cn/reactnative/modules/qq/QQModule.java:34: 错误: QQModule不是抽象的, 并且未覆盖ActivityEventListener中的抽象方法onActivityResult(int,int,Intent)
public class QQModule extends ReactContextBaseJavaModule implements IUiListener, ActivityEventListener {
注: /Users/xxx/xxx/xxx/app/android/xbiao/node_modules/react-native-qq/android/src/main/java/cn/reactnative/modules/qq/QQModule.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
1 个错误
:react-native-qq:compileReleaseJavaWithJavac FAILED

前端转RN新手，不懂安卓

**Comment by maagee** [comment]
错了，RN版本是0.32 不是0.29

**Comment by JoshYuJump** [comment]
文档里有写需要 0.33 +
> React Native的QQ登录插件, react-native版本需要0.33.0及以上
