### ISSUE TITLE
没有定义mReactInstanceManager

### ISSUE THREAD

**Issue by liuhong1happy** [reactnativecn/react-native-qq#46]
没有定义mReactInstanceManager，我需要怎么定义？

**Comment by guowei3** [comment]
不用定义那个，直接跑这个命令react-native link react-native-qq

**Comment by ganyangxing** [comment]
同样的问题，已经link了，还是报错
![image](https://user-images.githubusercontent.com/29500602/28260650-a7b5ca20-6b0e-11e7-9544-90635010a49e.png)

代码：
![image](https://user-images.githubusercontent.com/29500602/28260678-c5da99e0-6b0e-11e7-82ce-aeb6243c54f3.png)

**Comment by tdzl2003** [comment]
这几句话在新版本的RN中不需要添加了，删掉即可。
