### ISSUE TITLE
react-native-qqsdk is better

### ISSUE THREAD

**Issue by linytsysu** [reactnativecn/react-native-qq#48]
[react-native-qqsdk](https://github.com/iVanPan/react-native-qqsdk) is a better React Native wrapper around the Tencent QQ SDK. I suggest you use [react-native-qqsdk](https://github.com/iVanPan/react-native-qqsdk) instead of this one.

**Comment by chimumao** [comment]
I tried. Very bad. Lots of nosense files were installed, some of which name "tmp" with xxx@spam email in it. I guess it is a spam module.
