### ISSUE TITLE
QQAPI.login([scopes])

### ISSUE THREAD

**Issue by menghuanwd** [reactnativecn/react-native-qq#5]
scopes 是填写什么的啊

**Comment by tdzl2003** [comment]
- scopes: 登录所申请的权限，默认为get_simple_userinfo。 需要多个权限时，以逗号分隔。

已经补充文档

**Comment by menghuanwd** [comment]
能够给个例子吗？我没有做过第三方登录，不知道QQAPI.login([scopes])  具体怎么写。

**Comment by maagee** [comment]
_loginQQ(){
    QQAPI.login('get_simple_userinfo').then((res)=>{
      oauth_id = res.openid;
      access_token = res.access_token;
      alert(oauth_id);
    });
  }
