### ISSUE TITLE
reactnativecn的几个包文档以及内容更新都极其缓慢，使用还要折腾好久

### ISSUE THREAD

**Issue by sayhei** [reactnativecn/react-native-qq#54]
刚装了一个wechat 的，现在再试试qq，我去，要吐血了，更新较慢，无法现有react native

**Comment by rocwangv** [comment]
免费用别人的开源模块，竟然还这么多怨言，兄弟你可以的！

**Comment by tdzl2003** [comment]
建议issue提问时携带具体遇到的问题，我们维护的插件极多，RN版本迭代很快，不可能每次版本更新都测试所有的插件。遇到问题在issue里交流即可。
