### ISSUE TITLE
QQAPI在JS引用时报错

### ISSUE THREAD

**Issue by chimumao** [reactnativecn/react-native-qq#59]
编译没问题，JS启动时报错：undefined is not an object (evaluating QQAPI.isQQinstalled)。不知是什么问题？

**Comment by sunnylqm** [comment]
表示没有正确link或link后没有正确编译

**Comment by chimumao** [comment]
请问说明书上的这两条是重复的吗？

(2)在app/build.gradle里添加如下代码：
compile project(':react-native-qq')
(3)在android/app/build.gradle里的dependencies结构中添加如下代码：
dependencies{
    ... // 原本的代码
    compile project(':react-native-qq')
}

**Comment by chimumao** [comment]
Link报错信息如下（搞了两天了，(⊙﹏⊙)b）：
react-native link react-native-qq
Scanning 572 folders for symlinks in /Users/yexuhui/AwesomeProject/node_modules (23ms)
rnpm-install info Android module react-native-qq is already linked 
rnpm-install ERR! Something went wrong while linking. Error: Expected "/*" or ";" but "\"" found. 
Please file an issue here: https://github.com/facebook/react-native/issues

**Comment by chimumao** [comment]
已解决。真机调试没问题。。(⊙﹏⊙)b
