### ISSUE TITLE
RN 升级到 0.20 后报错

### ISSUE THREAD

**Issue by kinhunt** [reactnativecn/react-native-qq#6]
一开始说没有 es6 promisify 模块。安装该模块后能正常打开 RN 程序，调用 QQAPI.login 时报以下错：

Unhandled Promise Rejection (id: 0):
undefined is not an object (evaluating '_reactNativeQq2.default.login')

请问是什么问题？谢谢。

**Comment by kinhunt** [comment]
i am stupit

**Comment by produmpling** [comment]
@kinhunt 你怎么解决的？
