### ISSUE TITLE
ios版拿到的openid和android版不一样，而且在请求https://graph.qq.com/user/get_user_info时报invalid openid错。

### ISSUE THREAD

**Issue by kingctan** [reactnativecn/react-native-qq#63]
ios版拿到的openid和android版不一样，而且在请求https://graph.qq.com/user/get_user_info时报invalid openid错。android没问题。

**Comment by tdzl2003** [comment]
这很显然不是这个插件的问题。建议在腾讯开放平台寻找答案。
