### ISSUE TITLE
ios 在工程target的Build Phases->Link Binary with Libraries 出现问题，请教下大牛

### ISSUE THREAD

**Issue by 52myu** [reactnativecn/react-native-qq#7]
在工程target的Build Phases->Link Binary with Libraries中加入libRCTQQAPI.a、libiconv.tbd、libsqlite3.tbd、liz.tbd、libc++.tbd

liz.tbd没有找到……

**Comment by sunnylqm** [comment]
应该是libz吧

**Comment by 52myu** [comment]
恩对的
