### ISSUE TITLE
0.22.2的rn 如何调用包呢

### ISSUE THREAD

**Issue by 52myu** [reactnativecn/react-native-qq#8]
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data){
        super.onActivityResult(requestCode, resultCode, data);
        mReactInstanceManager.onActivityResult(requestCode, resultCode, data);
    }
在0.22.2中   这个方法  如何用呢

**Comment by tdzl2003** [comment]
0.19以上版本不需要些这几句了。

**Comment by litingjun2015** [comment]
您好：

我能够成功激活QQ登录（安卓），但resolve没输出，请问是什么原因？

```
QQAPI.login()
      .then((result)=>{
        console.log('QQAPI("get_simple_userinfo") result', result)
      })
      .catch((e)=>{
        console.error(e);
      })
```

我是 react-native: 0.34.1，是不是也不用加这几句？
can not resolve symbol mReactInstanceManager.

**Comment by yabinliu** [comment]
@litingjun2015   are you ok ?

**Comment by litingjun2015** [comment]
@yabinliu not ok...

**Comment by litingjun2015** [comment]
@yabinliu ok now. I guess app should be approved at http://open.qq.com/ firstly.
