### ISSUE TITLE
0.23.1 的rn 编译出错诶

### ISSUE THREAD

**Issue by 52myu** [reactnativecn/react-native-qq#9]
/node_modules/react-native-qq/android/build/intermediates/bundles/debug/AndroidManifest.xml:17:13-40 Error:
	Attribute meta-data#QQ_APPID@value at [debug] AndroidManifest.xml:17:13-40 requires a placeholder substitution but no value for <QQ_APPID> is provided.

**Comment by tdzl2003** [comment]
参考文档：

在android/app/build.gradle里，defaultConfig栏目下添加如下代码：

```
        manifestPlaceholders = [
            QQ_APPID: "<平台申请的APPID>"
        ]
```

你一定是缺少了这一段。
